<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne une observation avec ses dépendances
     * @param $espece
     * @return array
     */
    public function getEspeceWithJoin($espece){
        $qb = $this
            ->createQueryBuilder('a')
            ->addselect('a')
            ->leftJoin('a.espece', 'espece')
            ->addSelect('espece')
            ->leftJoin('espece.rang', 'rang')
            ->addSelect('rang')
            ->leftJoin('espece.habitat', 'habitat')
            ->addSelect('habitat')
            ->leftJoin('espece.fr', 'fr')
            ->addSelect('fr')
            ->andWhere('a.espece = :espece')
            ->setParameter('espece', $espece)
            ->orderBy('a.dcree', 'ASC');

        return $qb
            ->getQuery()
            ->getResult()
            ;

    }

    /**
     * Retourne une observation avec ses dépendances
     * @param $espece
     * @return array
     */
    public function getOneWithJoin($id){
        $qb = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.espece', 'espece')
            ->addSelect('espece')
            ->leftJoin('espece.rang', 'rang')
            ->addSelect('rang')
            ->leftJoin('espece.habitat', 'habitat')
            ->addSelect('habitat')
            ->leftJoin('espece.fr', 'fr')
            ->addSelect('fr')
            ->andWhere('a.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult()
            ;

    }

    /**
     * Retourne toutes les observation entre deux dates
     *
     * @param $datedebut
     * @param $datefin
     * @return array
     */
    public function extract($datedebut, $datefin){
        $qb = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.espece', 'espece')
            ->addSelect('espece')
            ->leftJoin('espece.rang', 'rang')
            ->addSelect('rang')
            ->leftJoin('espece.habitat', 'habitat')
            ->addSelect('habitat')
            ->leftJoin('espece.fr', 'fr')
            ->addSelect('fr')
            ->andWhere('a.dobs >= :datedebut')
            ->setParameter('datedebut', $datedebut)
            ->andWhere('a.dobs <= :datefin')
            ->setParameter('datefin', $datefin)
            ->andWhere('a.statut = :statut')
            ->setParameter('statut', "STATUT_VALIDE");

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    /**
     * Retourne les taxons en et leur nombre dans les observations
     *
     * @param string $recherche
     * @return array
     */
    public function getByAutoComplete($recherche){
        //$qb = $this->_em->createQuery('select count(o.id) as occurence, t.id, t.lb_nom, t.nom_vern, t.nom_vern_eng from AppBundle\Entity\Observation o right join AppBundle:Taxref t with o.espece_id = t.id WHERE t.lbNom like \'%'.$recherche.'%\' OR t.nomVern like \'%'.$recherche.'%\' OR t.nomVernEng like \'%'.$recherche.'%\' group by t.id' );
         /*   ->from('AppBundle:Observation', 'o')
        ->leftJoin('AppBundle:Taxref', 'a') // left join inversé = right join
                ->from('AppBundle:Taxref', 't')
        ->addSelect('count(o.id) as occurence')
        ->addSelect('t.id')
        ->addSelect('t.lbNom')
        ->addSelect('t.nomVern')
        ->addSelect('t.nomVernEng')*/
        //$qb->where('t.lbNom like :search OR t.nomVern like :search OR t.nomVernEng like :search');
        //->andWhere('o.statut = :statut')*/
        //$qb->groupBy('t.id');
        //$qb->setParameter('search', $recherche);
        //->setParameter('libelle', "occurence")
       // ->setParameter('statut', "STATUT_VALIDE");*/

        $qb = $this->createQueryBuilder('o')
            ->addSelect('count(o.id) as occurence')
            ->leftJoin('o.espece', 't')
            ->addSelect('t.id')
            ->addSelect('t.lbNom')
            ->addSelect('t.nomVern')
            ->addSelect('t.nomVernEng')
            ->groupBy('o.id')

        ;

        $query = $qb->getQuery();

        return $query->getArrayResult();

    }
}
