<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne une observation avec ses dépendances
     * @param $espece
     * @return array
     */
    public function getEspeceWithJoin($espece){
        $qb = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.espece', 'espece')
            ->addSelect('espece')
            ->leftJoin('espece.rang', 'rang')
            ->addSelect('rang')
            ->leftJoin('espece.habitat', 'habitat')
            ->addSelect('habitat')
            ->leftJoin('espece.fr', 'fr')
            ->addSelect('fr')
            ->andWhere('a.espece = :espece')
            ->setParameter('espece', $espece);

        return $qb
            ->getQuery()
            ->getResult()
            ;

    }

    /**
     * Retourne une observation avec ses dépendances
     * @param $espece
     * @return array
     */
    public function getOneWithJoin($id){
        $qb = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.espece', 'espece')
            ->addSelect('espece')
            ->leftJoin('espece.rang', 'rang')
            ->addSelect('rang')
            ->leftJoin('espece.habitat', 'habitat')
            ->addSelect('habitat')
            ->leftJoin('espece.fr', 'fr')
            ->addSelect('fr')
            ->andWhere('a.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult()
            ;

    }

}
