<?php

namespace AppBundle\Repository;

/**
 * TaxrefRangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRangRepository extends \Doctrine\ORM\EntityRepository
{
}
