<?php

namespace AppBundle\Repository;

/**
 * TaxrefStatutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefStatutsRepository extends \Doctrine\ORM\EntityRepository
{
}
