<?php

namespace AppBundle\Repository;

/**
 * TaxrefHabitatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefHabitatsRepository extends \Doctrine\ORM\EntityRepository
{
}
