# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: true
            simple_form:
                authenticator:  AppBundle\Security\UserAuthenticator
                login_path:  /login
                check_path:  /login_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
            provider: fnat_user_provider


    role_hierarchy:
        ROLE_NATURALISTE: [ ROLE_EXTRACT, ROLE_OBSERVATEUR ]
        ROLE_ADMIN: [ ROLE_NATURALISTE ]

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/participer, roles: ROLE_OBSERVATEUR }
        - { path: ^/participer/espace-naturaliste, roles: ROLE_NATURALISTE }
        - { path: ^/dashboard$, roles: ROLE_NATURALISTE }
        - { path: ^/dashboard/extraction-donnees, roles: ROLE_NATURALISTE }
        - { path: ^/dashboard, roles: ROLE_ADMIN }

    providers:
        fnat_user_provider:
            entity:
                class: AppBundle:User
                property: mail
        in_memory:
            memory:
                users:
                    simon@lhoir.me:  { password: $2y$13$UPfGQm0RWJVEA02FnL3kX.sS54jICD8oyvTlPAr5Wws8v5v1EOz9O, roles: 'ROLE_OBSERVATEUR' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Entity\User: bcrypt