# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: true
            form_login:
                login_path:  /connexion
                check_path:  /login_check
                default_target_path: fn_front_index
            provider: our_db_provider
        loging_firewall:
            pattern: ^/
            anonymous: true

    role_hierarchy:
        ROLE_NATURALISTE: ROLE_OBSERVATEUR
        ROLE_ADMIN: [ ROLE_NATURALISTE, ROLE_OBSERVATEUR ]

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: mail
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: bcrypt