# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
         Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
         ROLE_NATURALISTE: ROLE_OBSERVATEUR
         ROLE_ADMIN: [ROLE_OBSERVATEUR, ROLE_NATURALISTE ]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                user: { password: userpass, roles: ['ROLE_OBSERVATEUR']}
                naturaliste: { password: natpass, roles: ['ROLE_NATURALISTE']}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

