# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: true
            form_login:
                login_path:  /login
                check_path:  /login_check
            #provider: our_db_provider


    role_hierarchy:
        ROLE_NATURALISTE: ROLE_OBSERVATEUR
        ROLE_ADMIN: [ ROLE_NATURALISTE, ROLE_OBSERVATEUR ]

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/participer, roles: ROLE_OBSERVATEUR }
        - { path: ^/dashboard, roles: ROLE_ADMIN }

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: mail
        in_memory:
            memory:
                users:
                    simon@lhoir.me:  { password: motdepasse, roles: 'ROLE_OBSERVATEUR' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: plaintext